---
title: "HPC access"
format:
  html:
    page-layout: full
---


The Sandbox is collaborating with the two major academic high performance computing platforms in Denmark. Computerome is located at the Technical University of Denmark (and co-owned by the University of Copenhagen) while UCloud is owned by the University of Southern Denmark. These HPC platforms each have their own strengths which we leverage in the Sandbox in different ways.

## UCloud

[UCloud](https://cloud.sdu.dk/app/login) is a relatively new HPC platform that can be accessed by students at Danish universities (via a WAYF university login). It has a user friendly graphical user interface that supports straightforward project, user, and resource management. UCloud provides access to many tools via selectable Apps matched with a range of flexible compute resources. Check out UCloud's extensive user docs [here](https://docs.cloud.sdu.dk/index.html). 

The Sandbox is deploying training modules in this form such that any UCloud user can easily access Sandbox materials independently. The Sandbox is also hosting workshops and training events on UCloud in conjunction with in-person training. Click below for detailed instructions on accessing Sandbox apps. 

&nbsp;

 <p align="center">
  <a href="./UCloud.qmd" style="background-color: #4266A1; color: #FFFFFF; padding: 30px 20px; text-decoration: none; border-radius: 5px;">
    UCloud Guide for Sandbox apps
  </a>
</p>

&nbsp;


## GenomeDK

[GenomeDK](https://genome.au.dk/) is Aarhus University’s high‑performance computing facility for the life sciences-serving researchers, students, the public sector and companies with powerful, secure infrastructure and datamanagement tools. 

:::{.callout-note title="GenomeDK workshops at AU" collapse="true"}
Check out [GenomeDK Workshop Resources (AU)](https://hds-sandbox.github.io/GDKworkshops/) for access and an introduction to the HPC system and basic commands. 

GenomeDK workshop content (in development): 

- Some background
- GenomeDK’s ABC
- File System (FS) on GenomeDK
- Working with Files
- Project management
- Downloads and Copies
- Package/Environment management
- Running a Job
:::


## Computerome

[Computerome](https://computerome.dk/) is the home of many sensitive health datasets via collaborations between DTU, KU, Rigshospitalet, and other major health sector players in the Capital Region of Denmark. Computerome has recently launched their secure cloud platform, [DELPHI](https://computerome.dk/solutions/delphi), and in collaboration with the Sandbox has built a [Course Platform](https://computerome.dk/solutions/course-platform) on the same backbone such that courses and training can be conducted in the same environment as real research would be performed in the secure cloud. The Sandbox is supporting courses in the Course Platform, but it is also available for independent use by educators at Danish universities. Please see their website for more information on independent use and pricing, and [contact us](mailto:nhds_sandbox@sund.ku.dk) if you'd like to collaborate on hosting a course on Computerome. We can help with tool installation, environment testing, and user support (ranging from using the environment to course content if we have Sandbox staff with matching expertise).

Participants in courses co-hosted by the Sandbox can check [here](Computerome.qmd) for access instructions. 


## Any other computing cluster / local PC

Some of our modules are available in a containerized version on Docker Hub, making them accessible on any system, while others are specifically designed for UCloud. Additionally, some modules provide separate instructions for setting up environments locally or on an HPC system.

Find the docker images in https://hub.docker.com/u/hdssandbox. 



